profile: cover.out

local-prefix: "github.com/PixoVR/pixo-golang-clients/pixo-platform"

threshold:
  file: 0

  package: 13

  total: 71

exclude:
  paths:
    - ^*/spy.go
    - ^*/mock.go
    - ^legacy
    - ^platform-cli/main.go
    - ^platform-cli/cmd/root.go
    - ^platform-cli/src/ctx
    - ^platform-cli/src/editor
    - ^platform-cli/src/forms/fancy
    - ^platform-cli/src/mockserver
    - ^platform-cli/src/tui
