profile: cover.out

local-prefix: "github.com/PixoVR/pixo-golang-clients/pixo-platform"

threshold:
  file: 70

  package: 70

  total: 63

exclude:
  paths:
    - ^*/spy.go
    - ^*/mock.go
    - ^platform-cli/main.go
    - ^platform-cli/cmd/root.go
    - ^platform-cli/src/editor
    - ^platform-cli/src/forms/fancy
    - ^platform-cli/src/ctx
    - ^platform-cli/src/mockserver
