
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/pixo-platform"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/pixo-platform/cmd/platform-cli"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/vertex-ai"
    schedule:
      interval: "daily"
