profile: cover.out

local-prefix: "github.com/PixoVR/pixo-golang-clients/pixo-platform/platform-cli"

threshold:
  file: 54

  package: 73

  total: 81

exclude:
  paths:
    - ^main.go
    - ^cmd/root.go
    - ^src/ctx
    - ^src/editor
    - ^src/forms/fancy
    - ^src/mockserver
    - ^src/tui
