profile: cover.out

local-prefix: "github.com/PixoVR/pixo-golang-clients/pixo-platform/platform-cli"

threshold:
  file: 52

  package: 63

  total: 82

exclude:
  paths:
    - ^main.go
    - ^cmd/root.go
    - ^src/forms/fancy
    - ^src/editor
    - ^src/mockserver
