
Output create-user.gif

Require echo

Set Shell "bash"
Set FontSize 32
Set Width 1200
Set Height 600

Type "pixo users create" Enter
Sleep 1s
Type "Test" Sleep 500ms  Enter
Type "Developer" Sleep 500ms  Enter
Type "test-developer@pixovr.com" Sleep 500ms  Enter
Type "testdeveloper" Sleep 500ms  Enter
Type "" Sleep 500ms  Enter
Type "/dev" Sleep 500ms  Enter
Sleep 500ms
Type "/Pixo" Sleep 500ms  Enter

Sleep 5s
