# check the documentation at https://goreleaser.com

# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

before:
  hooks:
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: pixo
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch


brews:
    - name: pixo-cli
      folder: Formula
      repository:
        owner: PixoVR
        name: homebrew-pixo-golang-clients
      homepage: https://github.com/PixoVR/pixo-golang-clients
      description: Pixo Platform CLI tool
      url_template: "https://github.com/PixoVR/pixo-golang-clients/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

chocolateys:
  -
    # Your app's package name.
    # The value may not contain spaces or character that are not valid for a URL.
    # If you want a good separator for words, use '-', not  '.'.
    #
    # Default: ProjectName
    name: pixo-cli

    # IDs of the archives to use.
    # Empty means all IDs.
#    ids:
#      - foo
#      - bar

    # Your app's owner.
    # It basically means you.
    owners: Walker O'Brien

    # The app's title.
    # A human-friendly title of the package.
    #
    # Default: ProjectName
    title: Pixo Platform CLI

    # Your app's authors (probably you).
    authors: Walker O'Brien

    # Your app's project url.
    # It is a required field.
    project_url: https://example.com/

    # URL which is determined by the given Token (github,
    # gitlab or gitea).
    #
    # Default: depends on the git remote
    # Templates: allowed
    url_template: "https://github.com/PixoVR/pixo-golang-clients/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # App's icon.
    icon_url: 'https://rawcdn.githack.com/foo/bar/efbdc760-395b-43f1-bf69-ba25c374d473/icon.png'

    # Your app's copyright details.
    copyright: 2023 PixoVR Corp

    # App's license information url.
    license_url: https://github.com/PixoVR/pixo-golang-clients/blob/main/pixo-platform/cmd/platform-cli/LICENSE

    # Your apps's require license acceptance:
    # Specify whether the client must prompt the consumer to accept the package
    # license before installing.
    require_license_acceptance: false

    # Your app's source url.
    project_source_url: https://github.com/PixoVR/pixo-golang-clients/blob/main/pixo-platform/cmd/platform-cli

    # Your app's documentation url.
    docs_url: https://github.com/PixoVR/pixo-golang-clients/blob/main/pixo-platform/cmd/platform-cli/README.md

    # App's bugtracker url.
    bug_tracker_url: https://github.com/PixoVR/pixo-golang-clients/issues

    # Your app's tag list.
    tags: "foo bar baz"

    # Your app's summary:
    summary: CLI tool for interacting with the Pixo Platform

    # This the description of your chocolatey package.
    # Supports markdown.
    description: |
      {{ .ProjectName }} installer package.
      CLI tool for interacting with the Pixo Platform

    # Your app's release notes.
    # A description of the changes made in this release of the package.
    # Supports markdown. To prevent the need to continually update this field,
    # providing a URL to an external list of Release Notes is perfectly
    # acceptable.
    release_notes: "https://github.com/PixoVR/pixo-golang-clients/releases/tag/{{ .Version }}"

    # App's dependencies
    # The version is not required.
    dependencies:
      - id: nfpm
        version: 2.20.0

    # The api key that should be used to push to the chocolatey repository.
    #
    # WARNING: do not expose your api key in the configuration file!
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'

    # The source repository that will push the package to.
    source_repo: "https://push.chocolatey.org/"

    # Setting this will prevent goreleaser to actually try to push the package
    # to chocolatey repository, leaving the responsibility of publishing it to
    # the user.
    skip_publish: false