
name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pixo-platform
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.54
          install-mode: "goinstall"
          args: --timeout=30m
          working-directory: ./pixo-platform

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pixo-platform
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Tests
        run: |
          mkdir ~/.pixo
          go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
        env:
          TEST_PIXO_LIFECYCLE: dev
          TEST_PIXO_SECRET_KEY: ${{ secrets.DEV_SECRET_KEY }}
          TEST_PIXO_API_KEY: ${{ secrets.DEV_PIXO_API_KEY }}
          TEST_PIXO_USERNAME: ${{ secrets.SUPERADMIN_USERNAME }}
          TEST_PIXO_PASSWORD: ${{ secrets.SUPERADMIN_PASSWORD }}

      - name: Check Test Coverage
        run: |
          go install github.com/vladopajic/go-test-coverage/v2@latest
          go-test-coverage -config=./.coverage.yaml
