
name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pixo-platform

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.54
          install-mode: "goinstall"
          args: --timeout=30m
          working-directory: ./pixo-platform

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./pixo-platform

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Tests
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
        env:
          PIXO_LIFECYCLE: stage
          PIXO_REGION: na
          SECRET_KEY: ${{ secrets.STAGE_SECRET_KEY }}
          PIXO_API_KEY: ${{ secrets.STAGE_PIXO_API_KEY }}
          PIXO_USERNAME: ${{ secrets.SUPERADMIN_USERNAME }}
          PIXO_PASSWORD: ${{ secrets.SUPERADMIN_PASSWORD }}

#      - name: Check Test Coverage
#        uses: vladopajic/go-test-coverage@v2
#        with:
#          config: frontend/.coverage.yaml

permissions:
  contents: write
